#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/project" ] || [ -e "/etc/init/project.conf" ]; then
	if [ ! -e "/etc/init/project.conf" ]; then
		update-rc.d project defaults >/dev/null
	fi
	invoke-rc.d project start || exit $?
fi
# End automatically added section
