#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/project" ] || [ -e "/etc/init/project.conf" ]; then
	invoke-rc.d project stop || exit $?
fi
# End automatically added section
